/**
 * Insert a URL.
 *
 * @param text :p_url_url         The URL to be inserted.
 * @param int  :p_bul_id          The ID of the base URL of the URI to be inserted.
 * @param int  :p_url_id_referrer The ID of the URI the is referring to the URI.
 *
 * @type lastInsertId
 */
insert into TST_MONKEY_URL(url_url, bul_id, url_id_referrer)
values (:p_url_url, :p_bul_id, :p_url_id_referrer);

update TST_MONKEY_BASE_URL
set bul_pages = bul_pages + 1
where bul_id = :p_bul_id;
